#-------------------------------
# General Site Settings

title: Florian Determann
logo: icon.white.png
email: nanferten@gmail.com
address: Germany, Lower Saxony, Lingen

menu:
- {name: Stack, link: '/stack'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Hero Section

hero:
  hero-title: Florian Determann
  sub-title: Software Engineer at Atos.

social:
- {icon: "ti-github", link: "https://github.com/Nanferten"}
- {icon: "ti-email", link: "mailto:nanferten@gmail.com"}
- {icon: "ti-linkedin", link: "https://linkedin.com/in/florian-determann-51ab81199"}



#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Realistic. Inventive. Logical.



# About Page


#-------------------------------
# Skills Section

skills-title: Skills
skills:

- {name: Web Development, color: '#E91E63', value: '55%'}
- {name: Agile, color: '#8BC34A', value: '60%'}
- {name: Configuration-management, color: '#673AB7', value: '30%'}

#-------------------------------
# Experience Section

experience-title: Work Experience
experience:
- {name: Dual Student, icon: 'icon-1.png', date: 'Aug 2016 - Juli 2019', organization: 'Atos'}
- {name: Software Engineer, icon: 'icon-2.png', date: 'Juli 2019 -', organization: 'Atos'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: (B. Sc.) Business Informatics , date: '2019', organization: 'Osnabr√ºck University of Applied Sciences'}
- {name: Computer Science Expert , date: '2018', organization: 'IHK Emsland'}
- {name: Business High School (Abitur), date: '2016', organization: 'BBS Lingen Wirtschaft'}


#-------------------------------
# Services Section

services-title: Qualities
services:

- {
    name: Customer Engineering,
    icon: ti-world,
    description: 'Finding requirments and providing answers in cooperation with customer.',
    active: # Add true to select section
  }
- {
    name: Edge Enthusiast,
    icon: ti-rocket,
    description: 'Enjoying to work in promissing technologies and always willing to learn new ways.',
    active: true # Add true to select section
  }
- {
    name: Economic View,
    icon: ti-signal,
    description: 'Realistic view and good understanding of business needs and restriction.',
    active: # Add true to select section
  }

  #-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-item:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Programming language Section
programming-language-title: Programming languages
programming-language:
  - { name: Java, icon: 'java-original.svg', level: '' }
  - { name: C#, icon: 'csharp-plain.svg', level: '' }
  - { name: Typescript, icon: 'typescript-original.svg', level: '' }
  - { name: Python, icon: 'Python-logo-notext.svg', level: '' }

#-------------------------------
# Framework Section
framework-title: Frameworks
framework:
  - { name: Angular, icon: 'angular.svg', level: '' }
  - { name: .NET Core, icon: 'NET_Core_Logo.svg', level: '' }
  - { name: Spring, icon: 'springio-icon.svg', level: '' }

#-------------------------------
# Tools Section
tools-title: Tools
tools: 
  - { name: Docker, icon: 'docker-plain.svg', level: '', years: '' }
  - { name: Git, icon: 'git-original.svg', level: '', years: '' }
  - { name: Apache, icon: 'apache-original.svg', level: '', years: '' }
  - { name: MySql, icon: 'mysql-original.svg', level: '', years: '' }

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: nanferten@gmail.com