#-------------------------------
# General Site Settings

title: Florian Determann
logo: icon.white.png
email: nanferten@gmail.com
address: Germany, Lower Saxony, Lingen

menu:
- {name: About, link: '/about/'}
- {name: Contact, link: '/contact/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: "UA-139986962-1"


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! <br> I’m Florian

social:
- {icon: "ti-github", link: "https://github.com/Nanferten"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I'm currently an Software Engineer for Business Solutions. Further I discover the field of Data Science and build small projects.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#00BCD4', value: '40%'}
- {name: Web App Development, color: '#E91E63', value: '80%'}
- {name: Programming, color: '#8BC34A', value: '70%'}
- {name: Agile, color: '#673AB7', value: '90%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Dual Student, icon: 'icon-1.png', date: 'Aug 2016 - Juli 2019', organization: 'Atos'}
- {name: Software Engineer, icon: 'icon-2.png', date: 'Juli 2019 -', organization: 'Atos'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelor of Science - Business Informatics , date: '2019', organization: 'OSNABRÜCK UNIVERSITY OF APPLIED SCIENCES'}
- {name: Abitur Economic, date: '2016', organization: 'BBS Lingen Wirtschaft'}


#-------------------------------
# Services Section

services-title: Qualities
services:

- {
    name: Requirement Engineering,
    icon: ti-world,
    description: 'Finding requirments and providing answers for it is key for work.',
    active: # Add true to select section
  }
- {
    name: Software Development,
    icon: ti-rocket,
    description: 'My current provesion is to develop web application.',
    active: true # Add true to select section
  }
- {
    name: Economic View,
    icon: ti-signal,
    description: 'Always business in focus in providing services.',
    active: # Add true to select section
  }

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: nanferten@gmail.com